### ISSUE TITLE
Implement an L2TP IPsec VPN for android

### ISSUE THREAD

**Issue by Khsed4** [n8fr8/orbot#103]
Hello, everyone, I hope u do well.
I want to develop an L2TP IPsec VPN android application which it should connect to my own server (I have already a server ), which the application should connect to the server after it runs.
The issue is here: Can Orbot project help me to connect to the above type of VPN, or help me in some parts? 
I would really appreciate any help .

**Comment by n8fr8** [comment]
No, Orbot is not a traditional VPN. It uses the VPN framework on Android, but routes it over the Tor network instead. You could setup a Tor Onion Service on your server, and have your application use Tor and that address to connect. It is more secure than L2TP IPSec and has many other benefits related to privacy and surveillance defense.
