### ISSUE TITLE
App VPN Mode UI Problem

### ISSUE THREAD

**Issue by decode-dev** [n8fr8/orbot#107]
Text is overlapping with other apps in the "Apps VPN Mode" 
And also the UI is not centered.
Can the notification color be changed. 
![photo_2017-12-15_00-50-55](https://user-images.githubusercontent.com/6382146/34010291-2c19780e-e132-11e7-8883-9883ed6fd54f.jpg)

**Comment by bitmold** [comment]
oops i didn't realize there was already an issue open for this but I addressed these problems in #126

**Comment by bitmold** [comment]
This is now resolved on the master branch, but someone who can update the screenshots for Orbot on the play store should do so; it uses an image like the one posted above.
