### ISSUE TITLE
Orbot fails to start after installing 16.x ALPHA/BETA

### ISSUE THREAD

**Issue by pgerber** [n8fr8/orbot#112]
I just updated to Orbot 16.0.0 BETA 1 and it appears to be broken on my phone. I also tried to freshly install it and it didn't help. Orbot 16.0.0 ALPHA 1 doesn't work either.

## Error

Orbot fails to start, showing this error message in the log:

```
checking binary version: 0.3.1.8-openssl1.0.2k
upgrading binaries to latest version: 0.3.1.9-openssl1.0.2k
error finding exiting process: java.io.EOFException
```

## Device
model: Blackphone 2
OS: Android 6.0.1 (patch level 2017-12-01)

**Comment by n8fr8** [comment]
Can you try a complete uninstall and reboot? Otherwise, will look into the EOF Exception. Looks like something is locked down on the Blackphone.

**Comment by pgerber** [comment]
Uninstalled, rebooted and reinstalled, didn't help

**Comment by n8fr8** [comment]
and you are using the SDK23 version of the APK?

**Comment by n8fr8** [comment]
also, try enable debug log in Settings, and then swipe out from the right side in the main view, to get the full log output. Might be something more useful three.

**Comment by pgerber** [comment]
Yes, SDK23 and enabling debug logs didn't provide any more details but I was able to find some more details via logcat:

```
01-03 21:50:59.548  7046   973 I TorService: onCreate end
01-03 21:50:59.550  7046  1360 D Orbot   : checking binary version: 0.3.1.8-openssl1.0.2k
01-03 21:50:59.550  7046  1360 D Orbot   : upgrading binaries to latest version: 0.3.1.9-openssl1.0.2k
01-03 21:51:00.484  7046  1360 E Orbot   : error onBind
01-03 21:51:00.484  7046  1360 E Orbot   : java.io.EOFException
01-03 21:51:00.484  7046  1360 E Orbot   : 	at libcore.io.Streams.readFully(Streams.java:83)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:235)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at org.torproject.android.binary.TorResourceInstaller.streamToFile(TorResourceInstaller.java:187)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at org.torproject.android.binary.TorResourceInstaller.installGeoIP(TorResourceInstaller.java:165)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at org.torproject.android.binary.TorResourceInstaller.installResources(TorResourceInstaller.java:95)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at org.torproject.android.service.TorService.torUpgradeAndConfig(TorService.java:611)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at org.torproject.android.service.TorService.access$800(TorService.java:87)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at org.torproject.android.service.TorService$2.run(TorService.java:567)
01-03 21:51:00.484  7046  1360 E Orbot   : 	at java.lang.Thread.run(Thread.java:818)
01-03 21:51:00.484  7046  1360 D Orbot   : error finding exiting process: java.io.EOFException
```

**Comment by Diapolo** [comment]
I have the same issue on an Samsung Galaxy S4 (ks01lte) with LineageOS 13 (Android 6.0.1). Tried the same steps as @pgerber, wasn't able to fix it. Using Orbot 15.5.1-RC-2-multi is working fine for me.

**Comment by n8fr8** [comment]
Thanks, we'll have a new beta up soon with some changes that might fix things. An our side, we can't reproduce the issue on Nexus 5X or Samsung 6. Expanding our testing pool today.

**Comment by n8fr8** [comment]
New build posted: https://github.com/n8fr8/orbot/releases/tag/16.0.0-BETA-2

Please try a clean install

**Comment by pgerber** [comment]
Yes, BETA-2 fixes the issue, thanks. @Diapolo, does BETA-2 work on your phone too?

**Comment by n8fr8** [comment]
beta3, is now up as well, with some small tweaks to localization support, and a fix for notifications on Android Oreo: https://github.com/n8fr8/orbot/releases/tag/16.0.0-BETA-3

Thanks for the testing, @pgerber !

**Comment by Diapolo** [comment]
Beta 2 also fixed the issue for me :-), thank you!
