### ISSUE TITLE
Switch-to-new-Tor-Identity Feature removed?

### ISSUE THREAD

**Issue by Perflyst** [n8fr8/orbot#113]
Has the feature "Switch-to-new-Tor-Identity" been removed? I miss it in the newest version available.
Sometimes I get a very slow Relay/Exit Node and now I must disconnect and reconnect.
Before that, I could just turn the onion.

Can you please explain how I can do it in the newest version?
If you deleted this feature, why? Can you please add it again? It was very helpful.

**Comment by pgerber** [comment]
It has been moved to the notification (refresh button shown in the screenshot below). Depending on the Android your running, it can be hard to notice. On my phone there is no indicator to showing me that the message can be expanded unfortunately. However, pressing on the notification and swiping down expands it.

![screenshot_20180105-225457](https://user-images.githubusercontent.com/11895833/34630371-1c1fc9b2-f26c-11e7-8cfa-b4f2b3a777ea.png)

**Comment by n8fr8** [comment]
We are still playing with where to put it on the main screen... but it will be there by v16.0.1!

**Comment by pgerber** [comment]
I like having it in the notification but I'd like it even better when it was shown when the notification is collapsed. Perhaps that something worth considering.

**Comment by n8fr8** [comment]
The latest release has a small "refresh" icon in the action bar on the main screen.
