### ISSUE TITLE
When we have Tor 0.3.2.9 we no longer need Polipo

### ISSUE THREAD

**Issue by n8fr8** [n8fr8/orbot#115]
Tor 0.3.2.9 supports HTTP proxying directly. This means we no longer need Polipo for providing an HTTP proxy support to Android apps. Remove Polipo support in Orbot, and for bonus points, also remove it from the https://github.com/n8fr8/tor-android project (once that is at 0.3.2.9!)

**Comment by n8fr8** [comment]
Also, need to enable relevant torrc settings for Tor's HTTP proxy port

**Comment by bitmold** [comment]
As of commit `2b401050d0089fa4dd7527cc4ec840489c81dd4e` it looks like this issue can be closed!
