### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by GoodGuyNick** [n8fr8/orbot#122]
Crashing on CyanogenMod and LineageOS <14.1. All info and fix here - https://issuetracker.google.com/issues/64434571

**Comment by n8fr8** [comment]
There is a new beta release build to try:
https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-3

the "armeabi-v7a" APK should work for most people, or just get the "universal" one if you aren't sure.

**Comment by GoodGuyNick** [comment]
Working. Thank you.
