### ISSUE TITLE
Orbot is not up to date in Guardian Project or F-Droid Repositories in F-Droid App

### ISSUE THREAD

**Issue by herbsmn** [n8fr8/orbot#13]
I thought that F-Droid was the main way to get Orbot, but now that I'm looking at https://gitweb.torproject.org/n8fr8/orbot.git it seems like there are newer versions that have been coming out that aren't on F-Droid. Can you either fix the README to explain how to get Orbot outside of F-Droid or push the newest updates of this software to the F-Droid / Guardian Project Repositories? I'm curious to know why updates stopped getting pushed to F-Droid.

**Comment by n8fr8** [comment]
already replied to this in the other ticket
