### ISSUE TITLE
Manifest Cleanup

### ISSUE THREAD

**Issue by bitmold** [n8fr8/orbot#149]
Since we no longer use the `minaimalperm` product flavor, its manifest can be deleted. 

After that, we are left with the `fullperm` AndroidManifest which gets merged with the `main` AndroidManifest. A lot of the stuff in one of the two manifests that get merged with our exclusive `fullperm` product flavor end up being written in both, creating a messy set of manifest files. 

The manifest files would become a lot more maintainable were we to merge them into one file by hand, and not have to focus on maintaining two.

**Comment by n8fr8** [comment]
This is done now.
