### ISSUE TITLE
startup error: tor.so not found

### ISSUE THREAD

**Issue by pgerber** [n8fr8/orbot#150]
Orbot fails to start after update to *Orbot 16.0.2-BETA-1 with Tor 0.3.3.5-RC*. I tried both, the universal APK and the APK for armabi.

OS: Android 6.0.1

![signal-attachment-2018-05-12-142408](https://user-images.githubusercontent.com/11895833/39957280-fbe5040a-55df-11e8-9777-d9467471f7a7.png)

**Comment by rjmalagon** [comment]
Me too.
Inspecting app and data folders, I found that obfs4proxy.so and pndsd.so are missing too.
I extracted them from the base.apk and put in the lib folder (not an option for non rooted systems). It somewhat works, but vpn mode blows.
This happens with arm and universal flavors of the apk.

**Comment by n8fr8** [comment]
Can you both tell me more about your devices?

Are they rooted? which roms/OS version?

Is Orbot installed internally or externally (sd card)? Thanks!

**Comment by pgerber** [comment]
Mine is a Blackphone 2 with Silent OS 3.0.22 (Android 6.0.1) and Orbot is installed on internal storage and the device isn't rooted.

**Comment by rjmalagon** [comment]
My device is a Moto G3 (Osprey, 1GB Ram variant) with Lineage 14.1 (Android 7.1.2). Orbot is installed on internal storage, the device is rooted but disable by default.

I tested it on external storage too.

When installed, only libtun2socks.so appears on the lib folder.

**Comment by n8fr8** [comment]
Thank you both for the quick feedback. We are trying a new binary installation method that will make the APKs smaller and more efficient, so please bear with us!

**Comment by n8fr8** [comment]
New build to try: https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-2

**Comment by pgerber** [comment]
Tor functionality is working now. However, Orbot crashes when VPN mode is enabled.

[logcat.txt](https://github.com/n8fr8/orbot/files/2001954/logcat.txt)

**Comment by n8fr8** [comment]
@pgerber is the crash on the "Samsung Galaxy S4 running LineageOS 7.1.2" or another device?

**Comment by pgerber** [comment]
The logcat output is from the Samsung Galaxy but it crashes on the Blackphone 2 too.

**Comment by Le1b1** [comment]
Same here on a Google Pixel 2 running latest stock OS.
Could provide a logcat output if helpful.

**Comment by pgerber** [comment]
Just in case, here is the crash from the Blackphone 2 device:

[blackphone2.txt](https://github.com/n8fr8/orbot/files/2002238/blackphone2.txt)

**Comment by n8fr8** [comment]
Okay, another build, with some regenerated native code, and less binary size optimization!

https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-3

Thanks, all for the continued help.

**Comment by pgerber** [comment]
Working for me and hoping that's the case for @Le1b1 and @rjmalagon too.

> Thanks, all for the continued help.

No, thank you. You're the one doing all the work.

Yeah, v3 onion services support is here :)

**Comment by Le1b1** [comment]
Yes, it's fine now!
Thanks @n8fr8

**Comment by rjmalagon** [comment]
It works for me. WOW, you made it @n8fr8, under 10MB size APK and got 3.2+ TOR node. Awesome!

**Comment by pgerber** [comment]
Closing now that we have confirmation that it has been fixed all three of us. Thanks again @n8fr8.
