### ISSUE TITLE
Orbot 16.0.2-RC-1 Error on Startup 

### ISSUE THREAD

**Issue by Keridoo** [n8fr8/orbot#157]
I upgraded to Orbot 16.0.2-RC-1 via F-Droid today.

Expected behavior: Being able to connect without issues like before.

Actual behavior: Orbot being stuck on "Orbot starting". The log states:
`Orbot is starting...
Tor configuration did not verify: Error: -4 ERR= OUT=`

Temporary solution: Switch back to Orbot 16.0.0-RC-2-multi-SDK23

I'm on Android 7.1.1

**Comment by DJJosephJumper** [comment]
I am having the same problem, Android 7.1.1

**Comment by c0r3dump3d** [comment]
The same problem in Android 6.0 with the same version and  via F-Droid

**Comment by n8fr8** [comment]
Can you try installing the "universal" APK from here:
https://github.com/n8fr8/orbot/releases/tag/16.0.2-RC-1

https://github.com/n8fr8/orbot/releases/download/16.0.2-RC-1/Orbot-16.0.2-RC-1-fullperm-universal-release.apk

It might be an issue with F-Droid serving up the wrong architecture (armeabi vs armeabi-v7a)

**Comment by DJJosephJumper** [comment]
@n8fr8 Reinstalling the universal apk solved the problem. (Before I had installed the armeabi manually from the releases, I forgot to mention)

**Comment by Keridoo** [comment]
I can also confirm that the "universal" APK works. 

@n8fr8 What can be done to get F-Droid serving the right architecture?

**Comment by eighthave** [comment]
I removed the arm-only and x86-only APKs from the repo, so there is only the universal there now.

As for fixing that bug, someone needs to go through the F-Droid Client SQL code and make it understand that two APKs with the same _packageName_ and _versionCode_, but different binary architectures are not interchangeable.  I think that's the issue.
