### ISSUE TITLE
Orbot 16.0.3-BETA-1-tor-0.3.4.8 - Bridges do not work. 

### ISSUE THREAD

**Issue by yilmzfurkan** [n8fr8/orbot#174]
I am from a country where Tor is censored. The only way of connecting Tor is via bridges. "Orbot 16.0.2-RC-1" works great just updated to the beta release and I can't connect anymore. Tested the bridge on Desktop so the bridge is working. Here is the log:
`checking binary version: 0.3.4.8-openssl1.0.2p
Orbot is starting…
Orbot is starting…
updating settings in Tor service
updating torrc custom configuration...
success.
Orbot is starting…
Waiting for control port...
Connecting to control port: 37580
SUCCESS connected to Tor control port.
SUCCESS - authenticated to control port.
Starting Tor client… complete.
adding control port event handler
SUCCESS added control port event handler
Tor started; process id=11902
NOTICE: Delaying directory fetches: No running bridges 
WARN: We were supposed to connect to bridge '52.14.91.78:9443' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running. 
WARN: Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 2; recommendation warn; host 471103B54090AD326281BAE0CB383F08658EE36D at 52.14.91.78:9443) 
WARN: We were supposed to connect to bridge '52.14.91.78:9443' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running. 
WARN: Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 3; recommendation warn; host 471103B54090AD326281BAE0CB383F08658EE36D at 52.14.91.78:9443) `

Thanks in advance.

**Comment by yilmzfurkan** [comment]
Latest versions don't have this problem. Thanks.

**Comment by minutesinch** [comment]
> Latest versions don't have this problem. Thanks.

How You Say Latest versions don't have this problem???
