### ISSUE TITLE
Errors while setting up in eclipse

### ISSUE THREAD

**Issue by rajkotraja** [n8fr8/orbot#18]
i ran make -c /external after specifying NDK path in makefile in NDK.
i am getting these error in eclipse:

i ran make -c /external after specifying NDK path in makefile in NDK.

Description Resource    Path    Location    Type
ConfigEntry cannot be resolved to a type    TorService.java /Orbot/src/org/torproject/android/service   line 1697   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1697   Java Problem
ConfigEntry cannot be resolved to a type    TorService.java /Orbot/src/org/torproject/android/service   line 1699   Java Problem
ConfigEntry cannot be resolved to a type    TorService.java /Orbot/src/org/torproject/android/service   line 1700   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1567   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1677   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1678   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1693   Java Problem
The method orConnStatus(String, String) of type TorService must override or implement a supertype method    TorService.java /Orbot/src/org/torproject/android/service   line 1385   Java Problem
The method streamStatus(String, String, String) of type TorService must override or implement a supertype method    TorService.java /Orbot/src/org/torproject/android/service   line 1397   Java Problem
The method unrecognized(String, String) of type TorService must override or implement a supertype method    TorService.java /Orbot/src/org/torproject/android/service   line 1409   Java Problem
The method bandwidthUsed(long, long) of type TorService must override or implement a supertype method   TorService.java /Orbot/src/org/torproject/android/service   line 1421   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1341   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1353   Java Problem
The method message(String, String) of type TorService must override or implement a supertype method TorService.java /Orbot/src/org/torproject/android/service   line 1376   Java Problem
The method newDescriptors(List<String>) of type TorService must override or implement a supertype method    TorService.java /Orbot/src/org/torproject/android/service   line 1381   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1231   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1212   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1296   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1294   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1140   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1129   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1193   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1173   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1097   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1089   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1121   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1109   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1074   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 524    Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1088   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1088   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 475    Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 481    Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 166    Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 470    Java Problem
EventHandler cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 85 Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 92 Java Problem
The import net cannot be resolved   TorService.java /Orbot/src/org/torproject/android/service   line 36 Java Problem
The import net cannot be resolved   TorService.java /Orbot/src/org/torproject/android/service   line 37 Java Problem
The import net cannot be resolved   TorService.java /Orbot/src/org/torproject/android/service   line 35 Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1786   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1794   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1763   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1771   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1809   Java Problem
TorControlConnection cannot be resolved to a type   TorService.java /Orbot/src/org/torproject/android/service   line 1837   Java Problem

**Comment by n8fr8** [comment]
did you retrieve all the submodules?

git submodules update --init --recursive

**Comment by rajkotraja** [comment]
Yes, i have retrieved all sub modules, But as error is only in TorService.java, i guess, der is some problem in Tor external module setup, do i need to compile or make it separately.
Please see if you can find the error.

Thank you

**Comment by rajkotraja** [comment]
i ran make -c external once more, and here is terminal output.
It might help u spot the problem.

Thank you


arm-linux-androideabi-gcc --sysroot=/media/rajkotraja/e088678a-d0de-4517-ad79-e4bc8b50a535/android-ndk-r10e/platforms/android-16/arch-arm" ANDROID_DEV=/media/rajkotraja/e088678a-d0de-4517-ad79-e4bc8b50a535/android-ndk-r10e/platforms/android-16/arch-arm/usr depend && \
		make CC="/media/rajkotraja/e088678a-d0de-4517-ad79-e4bc8b50a535/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/media/rajkotraja/e088678a-d0de-4517-ad79-e4bc8b50a535/android-ndk-r10e/platforms/android-16/arch-arm" ANDROID_DEV=/media/rajkotraja/e088678a-d0de-4517-ad79-e4bc8b50a535/android-ndk-r10e/platforms/android-16/arch-arm/usr build_libs
: not found: 1: ./Configure: :
Configuring for android
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-krb5         [krb5-flavor not specified] OPENSSL_NO_KRB5
    no-libunbound   [experimental] OPENSSL_NO_LIBUNBOUND (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-rfc3779      [default]  OPENSSL_NO_RFC3779 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-shared       [default] 
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-zlib         [default] 
    no-zlib-dynamic [default] 
IsMK1MF=0
CC            =gcc
CFLAG         =-DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_END -mandroid -I$(ANDROID_DEV)/include -B$(ANDROID_DEV)/lib -O3 -fomit-frame-pointer -Wall
EX_LIBS       =-ldl
CPUID_OBJ     =mem_clr.o
BN_ASM        =bn_asm.o
EC_ASM        =
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_core.o aes_cbc.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =
ENGINES_OBJ   =
PROCESSOR     =
RANLIB        =/usr/bin/ranlib
ARFLAGS       =
PERL          =/usr/bin/perl
THIRTY_TWO_BIT mode
DES_UNROLL used
DES_INT used
BN_LLONG mode
RC4 uses uchar
RC4_CHUNK is unsigned long
BF_PTR used
make[1]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl'
e_os2.h => include/openssl/e_os2.h
making links in crypto...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto'
crypto.h => ../include/openssl/crypto.h
opensslv.h => ../include/openssl/opensslv.h
opensslconf.h => ../include/openssl/opensslconf.h
ebcdic.h => ../include/openssl/ebcdic.h
symhacks.h => ../include/openssl/symhacks.h
ossl_typ.h => ../include/openssl/ossl_typ.h
constant_time_test.c => ../test/constant_time_test.c
making links in crypto/objects...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/objects'
objects.h => ../../include/openssl/objects.h
obj_mac.h => ../../include/openssl/obj_mac.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/objects'
making links in crypto/md2...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/md2'
md2.h => ../../include/openssl/md2.h
md2test.c => ../../test/md2test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/md2'
making links in crypto/md4...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/md4'
md4.h => ../../include/openssl/md4.h
md4test.c => ../../test/md4test.c
md4.c => ../../apps/md4.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/md4'
making links in crypto/md5...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/md5'
md5.h => ../../include/openssl/md5.h
md5test.c => ../../test/md5test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/md5'
making links in crypto/sha...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/sha'
sha.h => ../../include/openssl/sha.h
shatest.c => ../../test/shatest.c
sha1test.c => ../../test/sha1test.c
sha256t.c => ../../test/sha256t.c
sha512t.c => ../../test/sha512t.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/sha'
making links in crypto/mdc2...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/mdc2'
mdc2.h => ../../include/openssl/mdc2.h
mdc2test.c => ../../test/mdc2test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/mdc2'
making links in crypto/hmac...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/hmac'
hmac.h => ../../include/openssl/hmac.h
hmactest.c => ../../test/hmactest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/hmac'
making links in crypto/ripemd...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ripemd'
ripemd.h => ../../include/openssl/ripemd.h
rmdtest.c => ../../test/rmdtest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ripemd'
making links in crypto/whrlpool...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/whrlpool'
whrlpool.h => ../../include/openssl/whrlpool.h
wp_test.c => ../../test/wp_test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/whrlpool'
making links in crypto/des...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/des'
des.h => ../../include/openssl/des.h
des_old.h => ../../include/openssl/des_old.h
destest.c => ../../test/destest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/des'
making links in crypto/aes...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/aes'
aes.h => ../../include/openssl/aes.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/aes'
making links in crypto/rc2...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rc2'
rc2.h => ../../include/openssl/rc2.h
rc2test.c => ../../test/rc2test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rc2'
making links in crypto/rc4...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rc4'
rc4.h => ../../include/openssl/rc4.h
rc4test.c => ../../test/rc4test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rc4'
making links in crypto/rc5...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rc5'
rc5.h => ../../include/openssl/rc5.h
rc5test.c => ../../test/rc5test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rc5'
making links in crypto/idea...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/idea'
idea.h => ../../include/openssl/idea.h
ideatest.c => ../../test/ideatest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/idea'
making links in crypto/bf...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/bf'
blowfish.h => ../../include/openssl/blowfish.h
bftest.c => ../../test/bftest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/bf'
making links in crypto/cast...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/cast'
cast.h => ../../include/openssl/cast.h
casttest.c => ../../test/casttest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/cast'
making links in crypto/camellia...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/camellia'
camellia.h => ../../include/openssl/camellia.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/camellia'
making links in crypto/seed...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/seed'
seed.h => ../../include/openssl/seed.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/seed'
making links in crypto/modes...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/modes'
modes.h => ../../include/openssl/modes.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/modes'
making links in crypto/bn...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/bn'
bn.h => ../../include/openssl/bn.h
bntest.c => ../../test/bntest.c
exptest.c => ../../test/exptest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/bn'
making links in crypto/ec...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ec'
ec.h => ../../include/openssl/ec.h
ectest.c => ../../test/ectest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ec'
making links in crypto/rsa...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rsa'
rsa.h => ../../include/openssl/rsa.h
rsa_test.c => ../../test/rsa_test.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rsa'
making links in crypto/dsa...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/dsa'
dsa.h => ../../include/openssl/dsa.h
dsatest.c => ../../test/dsatest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/dsa'
making links in crypto/ecdsa...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ecdsa'
ecdsa.h => ../../include/openssl/ecdsa.h
ecdsatest.c => ../../test/ecdsatest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ecdsa'
making links in crypto/dh...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/dh'
dh.h => ../../include/openssl/dh.h
dhtest.c => ../../test/dhtest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/dh'
making links in crypto/ecdh...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ecdh'
ecdh.h => ../../include/openssl/ecdh.h
ecdhtest.c => ../../test/ecdhtest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ecdh'
making links in crypto/dso...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/dso'
dso.h => ../../include/openssl/dso.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/dso'
making links in crypto/engine...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/engine'
engine.h => ../../include/openssl/engine.h
enginetest.c => ../../test/enginetest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/engine'
making links in crypto/buffer...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/buffer'
buffer.h => ../../include/openssl/buffer.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/buffer'
making links in crypto/bio...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/bio'
bio.h => ../../include/openssl/bio.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/bio'
making links in crypto/stack...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/stack'
stack.h => ../../include/openssl/stack.h
safestack.h => ../../include/openssl/safestack.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/stack'
making links in crypto/lhash...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/lhash'
lhash.h => ../../include/openssl/lhash.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/lhash'
making links in crypto/rand...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rand'
rand.h => ../../include/openssl/rand.h
randtest.c => ../../test/randtest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/rand'
making links in crypto/err...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/err'
err.h => ../../include/openssl/err.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/err'
making links in crypto/evp...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/evp'
evp.h => ../../include/openssl/evp.h
evp_test.c => ../../test/evp_test.c
evp_extra_test.c => ../../test/evp_extra_test.c
evptests.txt -> ../../test/evptests.txt
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/evp'
making links in crypto/asn1...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/asn1'
asn1.h => ../../include/openssl/asn1.h
asn1_mac.h => ../../include/openssl/asn1_mac.h
asn1t.h => ../../include/openssl/asn1t.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/asn1'
making links in crypto/pem...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pem'
pem.h => ../../include/openssl/pem.h
pem2.h => ../../include/openssl/pem2.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pem'
making links in crypto/x509...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/x509'
x509.h => ../../include/openssl/x509.h
x509_vfy.h => ../../include/openssl/x509_vfy.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/x509'
making links in crypto/x509v3...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/x509v3'
x509v3.h => ../../include/openssl/x509v3.h
v3nametest.c => ../../test/v3nametest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/x509v3'
making links in crypto/conf...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/conf'
conf.h => ../../include/openssl/conf.h
conf_api.h => ../../include/openssl/conf_api.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/conf'
making links in crypto/txt_db...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/txt_db'
txt_db.h => ../../include/openssl/txt_db.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/txt_db'
making links in crypto/pkcs7...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pkcs7'
pkcs7.h => ../../include/openssl/pkcs7.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pkcs7'
making links in crypto/pkcs12...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pkcs12'
pkcs12.h => ../../include/openssl/pkcs12.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pkcs12'
making links in crypto/comp...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/comp'
comp.h => ../../include/openssl/comp.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/comp'
making links in crypto/ocsp...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ocsp'
ocsp.h => ../../include/openssl/ocsp.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ocsp'
making links in crypto/ui...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ui'
ui.h => ../../include/openssl/ui.h
ui_compat.h => ../../include/openssl/ui_compat.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ui'
making links in crypto/krb5...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/krb5'
krb5_asn.h => ../../include/openssl/krb5_asn.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/krb5'
making links in crypto/cms...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/cms'
cms.h => ../../include/openssl/cms.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/cms'
making links in crypto/pqueue...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pqueue'
pqueue.h => ../../include/openssl/pqueue.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/pqueue'
making links in crypto/ts...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ts'
ts.h => ../../include/openssl/ts.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/ts'
making links in crypto/jpake...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/jpake'
jpake.h => ../../include/openssl/jpake.h
jpaketest.c => ../../test/jpaketest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/jpake'
making links in crypto/srp...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/srp'
srp.h => ../../include/openssl/srp.h
srptest.c => ../../test/srptest.c
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/srp'
making links in crypto/store...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/store'
store.h => ../../include/openssl/store.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/store'
making links in crypto/cmac...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/cmac'
cmac.h => ../../include/openssl/cmac.h
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto/cmac'
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto'
making links in ssl...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/ssl'
ssl.h => ../include/openssl/ssl.h
ssl2.h => ../include/openssl/ssl2.h
ssl3.h => ../include/openssl/ssl3.h
ssl23.h => ../include/openssl/ssl23.h
tls1.h => ../include/openssl/tls1.h
dtls1.h => ../include/openssl/dtls1.h
kssl.h => ../include/openssl/kssl.h
srtp.h => ../include/openssl/srtp.h
ssltest.c => ../test/ssltest.c
heartbeat_test.c => ../test/heartbeat_test.c
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/ssl'
making links in engines...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/engines'
making links in engines/ccgost...
make[3]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/engines/ccgost'
make[3]: Nothing to be done for `links'.
make[3]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/engines/ccgost'
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/engines'
making links in apps...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/apps'
make[2]: Nothing to be done for `links'.
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/apps'
making links in test...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/test'
make[2]: Nothing to be done for `links'.
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/test'
making links in tools...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/tools'
make[2]: Nothing to be done for `links'.
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/tools'
generating dummy tests (if needed)...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/test'
make[2]: Nothing to be done for `generate'.
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/test'
make[1]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl'

Configured for android.
make[1]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl'
making depend in crypto...
make[2]: Entering directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto'
/bin/sh: 1: ../util/domd: not found
make[2]: *** [depend] Error 127
make[2]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl/crypto'
make[1]: *** [depend] Error 1
make[1]: Leaving directory `/home/rajkotraja/Desktop/orbot/external/openssl'
make: *** [lib/libcrypto.a] Error 2
make: Leaving directory `/home/rajkotraja/Desktop/orbot/external'

**Comment by rajkotraja** [comment]
After trying to setup project from scratch on linux OS, i now have 
these error:

Description	Resource	Path	Location	Type
nativeLibraryDir cannot be resolved or is not a field	BinaryCommand.java	/RootCommands-Library/src/org/sufficientlysecure/rootcommands/command	line 55	Java Problem
The container 'Android Dependencies' references non existing library '/home/rajkotraja/Desktop/orbotnew/orbot/external/superuser-commands/RootCommands-Library/bin/rootcommands-library.jar'	Orbot		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	Orbot		Unknown	Java Problem
