### ISSUE TITLE
often see Polipo process id=-1   (15.1  RC-2 on M)  or cant connect via Socket connection 

### ISSUE THREAD

**Issue by c3ph3us** [n8fr8/orbot#22]
01-19 00:24:00.811 31994-31994 D/Orbot: checking binary version: 0.2.7.5-020120160125
01-19 00:24:00.812 31994-31994 D/Orbot: updating settings in Tor service
01-19 00:24:00.813 31994-31994 D/Orbot: updating torrc custom configuration...
01-19 00:24:00.813 31994-31994 D/Orbot: torrc.custom=ControlPortWriteToFile /data/data/org.torproject.android/app_bin/control.txt
                                        SOCKSPort 9050
                                        SafeSocks 0
                                        TestSocks 0
                                        WarnUnsafeSocks 1
                                        DisableNetwork 0
                                        Log debug syslog
                                        Log info syslog
                                        SafeLogging 0
                                        UseBridges 0
                                        GeoIPFile /data/data/org.torproject.android/app_bin/geoip
                                        GeoIPv6File /data/data/org.torproject.android/app_bin/geoip6
                                        EntryNodes {UK} 
                                        ExitNodes {ES}
                                        StrictNodes 1

....

01-19 00:24:07.341 31994-1123 D/Orbot: SUCCESS - authenticated to control port.
01-19 00:24:07.341 31994-1123 D/Orbot: adding control port event handler
01-19 00:24:07.343 31994-1123 D/Orbot: SUCCESS added control port event handler
01-19 00:24:07.345 31994-1123 D/Orbot: Tor started; process id=1177
01-19 00:24:07.345 31994-1123 D/Orbot: Starting polipo process
01-19 00:24:08.428 31994-1178 D/Orbot: Set background service to FOREGROUND
01-19 00:24:08.537 31994-1123 D/Orbot: Couldn't find Polipo process... retrying...
01-19 00:24:11.640 31994-1123 D/Orbot: Couldn't find Polipo process... retrying...
01-19 00:24:14.748 31994-1123 D/Orbot: Couldn't find Polipo process... retrying...
01-19 00:24:17.862 31994-1123 D/Orbot: Polipo process id=-1
01-19 00:24:34.549 31994-1178 D/Orbot: NOTICE: Application request when we haven't used client functionality lately. Optimistically trying directory fetches again. 
01-19 00:24:45.368 31994-1178 D/Orbot: NOTICE: Application request when we haven't used client functionality lately. Optimistically trying directory fetches again. 
01-19 00:25:27.126 31994-1178 D/Orbot: NOTICE: Application request when we haven't used client functionality lately. Optimistically trying directory fetches again. 
01-19 00:25:27.276 31994-1178 D/Orbot: NOTICE: Application request when we haven't used client functionality lately. Optimistically trying directory fetches again. 
01-19 00:25:34.655 31994-1178 D/Orbot: NOTICE: Application request when we haven't used client functionality lately. Optimistically trying directory fetches again. 
01-19 00:26:34.349 31994-1178 D/Orbot: NOTICE: Tried for 120 seconds to get a connection to 64.233.164.188:5228. Giving up. (waiting for circuit) 

ok  i use orbot with afwall+ as vpn 
1) first thing when i made any changes to orbot config i need to restart device to gain internet access  (see above log) 
2) second matter i cant read resource via socket 
- i can connect / send data (as bellow probably to orbot only)  
  
  ```
            socketInetAddress = new InetSocketAddress(_url.getHost(), _url.getPort());
            _socket = new Socket(Proxy.NO_PROXY);
            _socket.connect(socketInetAddress);  // OK 
            .. write  flush to socket // OK 
            while ((red =_socket.getInputStream().read(buffer)) > -1) {   // EXCEPTION THROWN
                     ...//
            } 
  ```
  
  java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
  when i try read from connection  or set no socket  proxy 

![soc1](https://cloud.githubusercontent.com/assets/10565704/12405759/43c3a57a-be47-11e5-8a86-8b1a2187b30c.png)

01-19 00:57:41.042 7921-7993/? D/Orbot: NOTICE: We tried for 15 seconds to connect to ' dest ip  xxxxx ' using exit $CEA791C0D90387F77B3068B899A39580FAFAB695~TheBlueCat at 62.57.160.237. Retrying on a new circuit. 
   ...    NOTICE: Tried for 125 seconds to get a connection to xxxxxxx:80. Giving up. 
- when i set proxy 
  
  ```
   InetSocketAddress proxyInetAddress = new InetSocketAddress("localhost", 9050);
   Proxy proxy = new Proxy(Proxy.Type.SOCKS,proxyInetAddress);
   _socket = new Socket(proxy);
   _socket.connect(socketInetAddress);   // THROWS 
  ```
  
  java.io.IOException: Failure to connect to SOCKS server  
  class com.android.server.NetworkManagementSocketTagger$SocketTags
  
  NOTICE: We tried for 15 seconds to connect to 'xxx.xxx.xxx.xxx' using exit $CEA791C0D90387F77B3068B899A39580FAFAB695~TheBlueCat at 62.57.160.237. Retrying on a new circuit. 
  NOTICE: Tried for 120 seconds to get a connection to xxx.xxx.xxx.xxx Giving up. 
- when i set Proxy to HTTP  while create socket i get 
  java.lang.IllegalArgumentException: Invalid proxy: HTTP@localhost/127.0.0.1:8118

3) i set both afwall & orbot to use build in iptables 

what services/ apps need have access to network to function as vpn / orbot 

1) i set in afwall+ access
- for VPN to apps 
- orbot access to lan/wifi/cell/vpn 

do i need  vpn network / kernel / sharing dns dhcp / ntp / root apps enabled on any  type of connection? 

what about proxy handler / html browser / captive portal ?

**Comment by c3ph3us** [comment]
second try 

01-19 00:47:08.594 2048-2109/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.torproject.android/.OrbotMainActivity (has extras)} from uid 10021 on display 0
01-19 00:47:08.671 2048-2068/? I/ActivityManager: Start proc 7921:org.torproject.android/u0a132 for activity org.torproject.android/.OrbotMainActivity
01-19 00:47:08.795 7921-7921/? I/Orbot: setNewLocale complete: locale: en Locale.getDefault: pl
01-19 00:47:09.048 7921-7921/? D/Orbot: checking binary version: 0.2.7.5-020120160125
01-19 00:47:09.049 7921-7921/? D/Orbot: updating settings in Tor service
01-19 00:47:09.050 7921-7921/? D/Orbot: updating torrc custom configuration...
01-19 00:47:09.050 7921-7921/? D/Orbot: torrc.custom=ControlPortWriteToFile /data/data/org.torproject.android/app_bin/control.txt
                                        SOCKSPort 9050
                                        SafeSocks 0
                                        TestSocks 0
                                        WarnUnsafeSocks 1
                                        DisableNetwork 0
                                        Log debug syslog
                                        Log info syslog
                                        SafeLogging 0
                                        UseBridges 0
                                        GeoIPFile /data/data/org.torproject.android/app_bin/geoip
                                        GeoIPv6File /data/data/org.torproject.android/app_bin/geoip6
                                        EntryNodes {NL} 
                                        ExitNodes {ES}
                                        StrictNodes 1
01-19 00:47:09.052 7921-7921/? D/Orbot: success.
01-19 00:47:09.056 7921-7938/? D/Orbot: Waiting for control port...
01-19 00:47:09.056 7921-7938/? D/Orbot: Reading control port config file: /data/data/org.torproject.android/app_bin/control.txt
01-19 00:47:09.058 7921-7938/? D/Orbot: Connecting to control port: 54637
01-19 00:47:09.064 7921-7921/? D/VPNEnableActivity: prompting user to start Orbot VPN
01-19 00:47:09.180 7921-7943/? D/Orbot: enabling VPN Proxy
01-19 00:47:09.230 7921-7921/? D/Orbot: handleIntents android.intent.action.MAIN
01-19 00:47:09.262 7921-7921/? D/OrbotVpnService: starting OrbotVPNService service!
01-19 00:47:09.655 7921-7948/? D/Orbot: Orbot is starting…
01-19 00:47:09.725 7921-7948/? D/Orbot: updating settings in Tor service
01-19 00:47:09.726 7921-7948/? D/Orbot: updating torrc custom configuration...
01-19 00:47:09.726 7921-7948/? D/Orbot: torrc.custom=ControlPortWriteToFile /data/data/org.torproject.android/app_bin/control.txt
                                        SOCKSPort 9050
                                        SafeSocks 0
                                        TestSocks 0
                                        WarnUnsafeSocks 1
                                        DisableNetwork 0
                                        Log debug syslog
                                        Log info syslog
                                        SafeLogging 0
                                        UseBridges 0
                                        GeoIPFile /data/data/org.torproject.android/app_bin/geoip
                                        GeoIPv6File /data/data/org.torproject.android/app_bin/geoip6
                                        EntryNodes {NL} 
                                        ExitNodes {ES}
                                        StrictNodes 1
01-19 00:47:09.728 7921-7948/? D/Orbot: success.
01-19 00:47:09.729 7921-7948/? D/Orbot: /data/data/org.torproject.android/app_bin/tor DataDirectory /data/data/org.torproject.android/app_data --defaults-torrc /data/data/org.torproject.android/app_bin/torrc -f /data/data/org.torproject.android/app_bin/torrc.custom
01-19 00:47:10.061 7921-7938/? D/Orbot: Reading control port config file: /data/data/org.torproject.android/app_bin/control.txt
01-19 00:47:10.062 7921-7938/? D/Orbot: Connecting to control port: 54637
01-19 00:47:11.065 7921-7938/? D/Orbot: Reading control port config file: /data/data/org.torproject.android/app_bin/control.txt
01-19 00:47:11.066 7921-7938/? D/Orbot: Connecting to control port: 54637
01-19 00:47:12.488 7921-7948/? D/Orbot: Waiting for control port...
01-19 00:47:12.489 7921-7948/? D/Orbot: Reading control port config file: /data/data/org.torproject.android/app_bin/control.txt
01-19 00:47:12.524 7921-7948/? D/Orbot: Connecting to control port: 52899
01-19 00:47:12.528 7921-7948/? D/Orbot: SUCCESS connected to Tor control port.
01-19 00:47:16.002 7921-7948/? D/Orbot: SUCCESS - authenticated to control port.
01-19 00:47:16.002 7921-7948/? D/Orbot: adding control port event handler
01-19 00:47:16.005 7921-7948/? D/Orbot: SUCCESS added control port event handler
01-19 00:47:16.010 7921-7948/? D/Orbot: Tor started; process id=7992
01-19 00:47:16.010 7921-7948/? D/Orbot: Starting polipo process
01-19 00:47:17.148 7921-7948/? D/Orbot: Couldn't find Polipo process... retrying...
01-19 00:47:17.316 7921-7993/? D/Orbot: Set background service to FOREGROUND
01-19 00:47:17.321 7921-7993/? D/Orbot: NOTICE: 11 entries in guards 
01-19 00:47:17.321 7921-7993/? D/Orbot: Circuit (1) LAUNCHED: 
01-19 00:47:17.322 7921-7993/? D/Orbot: orConnStatus (Unnamed): LAUNCHED
01-19 00:47:17.376 7921-7993/? D/Orbot: NOTICE: Bootstrapped 85%: Finishing handshake with first hop 
01-19 00:47:17.627 7921-7993/? D/Orbot: NOTICE: Bootstrapped 90%: Establishing a Tor circuit 
01-19 00:47:17.629 7921-7993/? D/Orbot: orConnStatus (Unnamed): CONNECTED
01-19 00:47:17.724 7921-7993/? D/Orbot: Circuit (1) EXTENDED: Unnamed
01-19 00:47:17.917 7921-7993/? D/Orbot: Circuit (1) EXTENDED: Unnamed > cloehle3
01-19 00:47:18.093 7921-7993/? D/Orbot: Circuit (2) LAUNCHED: 
01-19 00:47:18.185 7921-7993/? D/Orbot: Circuit (2) EXTENDED: Unnamed
01-19 00:47:18.302 7921-7993/? D/Orbot: Circuit (1) EXTENDED: Unnamed > cloehle3 > TheBlueCat
01-19 00:47:18.307 7921-7993/? D/Orbot: Circuit (1) BUILT: Unnamed > cloehle3 > TheBlueCat
01-19 00:47:18.308 7921-7993/? D/Orbot: NOTICE: Tor has successfully opened a circuit. Looks like client functionality is working. 
01-19 00:47:18.308 7921-7993/? D/Orbot: NOTICE: Bootstrapped 100%: Done 
01-19 00:47:18.377 7921-7993/? D/Orbot: Circuit (2) EXTENDED: Unnamed > xzdsb
01-19 00:47:18.606 7921-7993/? D/Orbot: Circuit (2) EXTENDED: Unnamed > xzdsb > TheBlueCat
01-19 00:47:18.607 7921-7993/? D/Orbot: Circuit (2) BUILT: Unnamed > xzdsb > TheBlueCat
01-19 00:47:19.108 7921-7993/? D/Orbot: Circuit (3) LAUNCHED: 
01-19 00:47:19.192 7921-7993/? D/Orbot: Circuit (3) EXTENDED: Unnamed
01-19 00:47:19.571 7921-7993/? D/Orbot: Circuit (3) EXTENDED: Unnamed > cvokk
01-19 00:47:19.743 7921-7993/? D/Orbot: Circuit (3) EXTENDED: Unnamed > cvokk > torpidsDEmyloc1
01-19 00:47:19.743 7921-7993/? D/Orbot: Circuit (3) BUILT: Unnamed > cvokk > torpidsDEmyloc1
01-19 00:47:20.081 7921-7993/? D/Orbot: Circuit (4) LAUNCHED: 
01-19 00:47:20.175 7921-7993/? D/Orbot: Circuit (4) EXTENDED: Unnamed
01-19 00:47:20.238 7921-7948/? D/Orbot: Couldn't find Polipo process... retrying...
01-19 00:47:20.466 7921-7993/? D/Orbot: Circuit (4) EXTENDED: Unnamed > GWproject
01-19 00:47:20.473 7921-7998/? D/Orbot: 62.57.160.237 Spain (VODAFONE ONO, S.A.)
01-19 00:47:20.600 7921-7993/? D/Orbot: Circuit (4) EXTENDED: Unnamed > GWproject > kittensOnTor
01-19 00:47:20.600 7921-7993/? D/Orbot: Circuit (4) BUILT: Unnamed > GWproject > kittensOnTor
01-19 00:47:22.363 7921-7998/? D/Orbot: 62.57.160.237 Spain (VODAFONE ONO, S.A.)
01-19 00:47:23.340 7921-7948/? D/Orbot: Couldn't find Polipo process... retrying...
01-19 00:47:23.934 7921-7998/? D/Orbot: 185.15.244.124 Germany (myLoc managed IT AG)
01-19 00:47:25.492 7921-7998/? D/Orbot: 81.7.16.31 Germany (ISPpro Internet KG)
01-19 00:47:26.431 7921-7948/? D/Orbot: Polipo process id=-1

**Comment by c3ph3us** [comment]
01-19 00:46:49.073 7457-7873/? D/Orbot: SUCCESS connected to Tor control port.
01-19 00:46:51.364 2048-2099/? W/ActivityManager: Exception when unbinding service org.torproject.android/.vpn.OrbotVpnService
                                                  android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                      at android.os.BinderProxy.transact(Binder.java:503)
                                                      at android.app.ApplicationThreadProxy.scheduleUnbindService(ApplicationThreadNative.java:956)
                                                      at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:1874)
                                                      at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:926)
                                                      at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:16246)
                                                      at android.app.ContextImpl.unbindService(ContextImpl.java:1352)
                                                      at com.android.server.connectivity.Vpn$1.interfaceRemoved(Vpn.java:753)
                                                      at com.android.server.NetworkManagementService.notifyInterfaceRemoved(NetworkManagementService.java:419)
                                                      at com.android.server.NetworkManagementService.-wrap7(NetworkManagementService.java)
                                                      at com.android.server.NetworkManagementService$NetdCallbackReceiver.onEvent(NetworkManagementService.java:783)
                                                      at com.android.server.NativeDaemonConnector.handleMessage(NativeDaemonConnector.java:128)
                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                      at android.os.Looper.loop(Looper.java:148)
                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                      at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by c3ph3us** [comment]
ok i have managed to trace that the problem is that  some parts of network are unreachable from other as u use tor :D (internet is no longer word wide web :/// ) 
does orbot can inform somehow (not by reset by peer ?)  that route is unreachable ?

**Comment by c3ph3us** [comment]
@n8fr8 
btw. how Tor handles request proxied by ClaudFlare? 

as i said in my prev post some resources are not reachable from different parts of internet
how then "Retrying on a new circuit."  is realized for SOCKET/HTTP request ?

**Comment by n8fr8** [comment]
Polipo is on longer included, as tor now supports an HTTP proxy directly
