### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by randinterval** [n8fr8/orbot#29]
Hi,
While trying to build the app, I get this error:
nsd': No such file
Makefile:298: recipe for target 'assets' failed
make: [assets] Error 1 (ignored)
zip ../assets/armeabi/pdnsd.mp3 ../libs/armeabi/pdnsd
    zip warning: name not matched: ../libs/armeabi/pdnsd

zip error: Nothing to do! (../assets/armeabi/pdnsd.mp3)
Makefile:298: recipe for target 'assets' failed
make: [assets] Error 12 (ignored)
rm ../libs/armeabi/pdnsd
rm: cannot remove ‘../libs/armeabi/pdnsd’: No such file or directory
Makefile:298: recipe for target 'assets' failed
make: [assets] Error 1 (ignored)
make: Leaving directory '/home/saad/Desktop/orbot/external'

What could be the issue?

**Comment by arrase** [comment]
Same problem here, any solutions?

Thanks

**Comment by n8fr8** [comment]
You should run ndk-build first within the /orbotservice directory
