### ISSUE TITLE
Update OpenSSL

### ISSUE THREAD

**Issue by AppAndro** [n8fr8/orbot#45]
According To Google Play, There Is A Vulnerability In Older Versions of OpenSSL. 
So, Orbot Needs An Update.

Thanks

**Comment by n8fr8** [comment]
We are not vulnerable to the issue, due to the way Tor uses OpenSSL.

That said, we will be updating soon to keep up to date with the latest core Tor release.

**Comment by dolar2006** [comment]
the problem is solved?
