### ISSUE TITLE
Orbot not working correctly on Android 7.0

### ISSUE THREAD

**Issue by horin** [n8fr8/orbot#50]
Hi,
after upgrading my Nexus 5X to Android 7.0 Orbot doesnt work correctly. It can connect as expected but it wont disconnect. So if I try to turn Orbot off it keeps turning on because for some reason it cant stop listeners on 9050. In my opinion the problem is with getting polipo and other processes ID. I am facing this issue myself and I still wasnt able to solve it. It is because at Android 7.0 Google has strictly restricted process policy. It means that you cannot get process ID (it always returns -1) and therefore there is probably problem communicating with these processes. I have heard reports from other user (I even think that developer of Copperhead OS mentioned that he is facing this issue with orbot on latest copperhead build with android 7.0) about having this issue.

**Comment by n8fr8** [comment]
Work is already well underway:
https://github.com/n8fr8/orbot/tree/dev_gradle
