### ISSUE TITLE
Can't build Orbot on AndroidStudio

### ISSUE THREAD

**Issue by horin** [n8fr8/orbot#53]
I am tryting to build latest dev_gradle branch on android studio. Importing gradle project into AS works as expected without any problems. But after I press Make in AS I get an error saying that config.h is missing. I am using latest NDK and latest Android Studio with Gradle plugin 2.2. Am I supposed to build orbot using different NDK version or what is the problem? Also doest the old instructions about building still aply? Because if I do make -C external I get an error saying that recipe for local_depend on openssl failed even that I have makedepend installed. 

Maybe BUILD file should really be updated to gradle/android studio version so we can test new comits and try them on newest Android 7.0.

Thanks in forward for reply

**Comment by mohabinventor** [comment]
hay horin
for two days i can't solve the same problem, did you manage to find answer?

**Comment by n8fr8** [comment]
It doesn't build yet with the NDK entirely. You need to follow the BUILD instructions. You still need to run the "	git submodule update --init --recursive" and so on for now, before you build the externals.

**Comment by mohabinventor** [comment]
what exactly you mean by that 

> It doesn't build yet with the NDK entirely. You need to follow the BUILD instructions.

**Comment by n8fr8** [comment]
Read the document here: https://github.com/n8fr8/orbot/blob/master/BUILD

You need to setup some build variables, and then run "make -C external"

We are working to move the binary build process out of this project, and into a separate gradle dependency, so that if you are not interested in building the binaries, you don't have to.

**Comment by mohabinventor** [comment]
ok thanx 
off topic question `i will work on that project i just started! do i need to learn C`
my goal is learn how it work, fix bugs, and maybe as something new.
