### ISSUE TITLE
there are many mistaks in source code, will my effort be merged?

### ISSUE THREAD

**Issue by mohabinventor** [n8fr8/orbot#57]
my first time to participate to open source.
I don't know if changes could easily get merged to main project (after reviewing)

reading through the source many bad practises, bad styling, unused code(many), and  nonsense code like defining public final static in interface. 

should I change any mistake will my changes be reviewed and merged to main project?

**Comment by arrase** [comment]
INMO you are right, there some ugly blocks of code but in other hand a massive refactor of the project can be a conflicts nightmare for other contributors, and would be a very unpopular measure

I think than projects like this, who has a very common IDE for developers with capability to auto-indent and code formating, should share a file with the configurarion of the code style for import into IDE.

That was always a friction point in all the projects i ever collaborate.

My advice is do not do it though it would be nice in a perfect future :)

**Comment by n8fr8** [comment]
Over time let's all work toward better styling and formatting, but yes, not all at once!
