### ISSUE TITLE
App crash when disable "Apps VPN Mode"

### ISSUE THREAD

**Issue by arrase** [n8fr8/orbot#65]
Flow:

- Enable Apps VPN Mode
- Do not select any app
- Disable Apps VPN Mode

...and the App crash

**Comment by arrase** [comment]
12-06 14:56:41.901 27250 27250 D AndroidRuntime: Shutting down VM
12-06 14:56:41.902 27250 27250 E AndroidRuntime: FATAL EXCEPTION: main
12-06 14:56:41.902 27250 27250 E AndroidRuntime: Process: org.torproject.android, PID: 27250
12-06 14:56:41.902 27250 27250 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.torproject.android-1/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libtun2socks.so"
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at org.torproject.android.service.vpn.Tun2Socks.<clinit>(Tun2Socks.java:35)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at org.torproject.android.service.vpn.Tun2Socks.init(Tun2Socks.java:60)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at org.torproject.android.service.vpn.OrbotVpnManager.<init>(OrbotVpnManager.java:96)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at org.torproject.android.service.vpn.TorVpnService.onCreate(TorVpnService.java:29)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3165)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6095)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-06 14:56:41.902 27250 27250 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-06 14:56:41.905  6900 13218 W ActivityManager:   Force finishing activity org.torproject.android/.OrbotMainActivity

**Comment by arrase** [comment]
is me, not Orbot ...yup!

**Comment by kshmr** [comment]
@arrase I have same problem, how to resolve that?
