### ISSUE TITLE
Torpolipo.conf edit error

### ISSUE THREAD

**Issue by ghost** [n8fr8/orbot#78]
Hi all,

This is 100 percent reproducible.

1. Stop Orbot, if already started.
2. Edit the torpolipo.conf at data/data/org.torproject.android/app_bin.
3. Apply changes.
4. Open Orbot.
5. Right-swipe to check the log.
6. Notice Orbot has reverted your changes made to torpolipo.conf, ex. proxyPort=8123 back to proxyPort=8118.

Why are the polipo proxy config settings hard-coded in Orbot? Polipo should be configurable to the end user in this instance.

Please consider an alternative update build that allows this.

Also, there's maybe a typo in the default torpolipo.conf included in version 15.4.2-RC-1-multi-SDK-16, which lists the socksParentProxy at "localhost-'inserted-forward-slash-before-colon-puncuation':9050". Shouldn't this be socksParentProxy="localhost:9050"?

**Comment by n8fr8** [comment]
We've removed polipo as Tor now directly supports an HTTP proxy
