### ISSUE TITLE
Can not update submodules 

### ISSUE THREAD

**Issue by FarhanAhmad** [n8fr8/orbot#86]
Hi, I ran following command:
git clone --recurse-submodules htts://github.com/n8fr8/orbot.git

everything is ok, except clonning into 'tor' submodule. Error showing is:

unable to access 'https://git.torproject.org/git/tor.git/': gnutls_handshake() failed: Error in the pull function.

Do I need to put some login info ?

**Comment by n8fr8** [comment]
Try again? Not sure. You don't need login. It is a public repo, which you can find on the web here:
https://gitweb.torproject.org/tor.git

You could try cloning this instead: https://git.torproject.org/tor.git
